(()=>{'use strict';
const API='https://ceybreez-contact-api.ceybreez.workers.dev';
const PAGES={home:'../../index.html',villas:'../../villas.html',homestays:'../../homestays.html',apartments:'../../apartments.html',tours:'../../tours.html','tour-details':'../../tour-details.html',services:'../../services.html',contact:'../../contact.html',privacy:'../../privacy.html',terms:'../../terms.html','404':'../../404.html'};
const $=id=>document.getElementById(id), frame=$('preview');
const state={page:'home',device:'desktop',selected:'',styles:{},custom:[],deleted:[],recordId:'',history:[],future:[]};
const token=()=>localStorage.getItem('CEYBREEZ_ADMIN_TOKEN')||'';
const headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token()}`,'X-Admin-Token':token()});
const doc=()=>frame.contentDocument; const esc=s=>CSS.escape(String(s||''));
function status(t,type=''){const n=$('status');n.textContent=t;n.className='status '+type}
function selector(el){if(el===doc().body)return'body';if(el.dataset.pbKey)return`[data-pb-key="${esc(el.dataset.pbKey)}"]`;if(el.id)return`#${esc(el.id)}`;const path=[];let n=el;while(n&&n!==doc().body&&path.length<6){let p=n.tagName.toLowerCase();const cls=[...n.classList].filter(c=>!c.startsWith('pb-editor')).slice(0,2);if(cls.length)p+='.'+cls.map(esc).join('.');const sib=n.parentElement?[...n.parentElement.children].filter(x=>x.tagName===n.tagName):[];if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(n)+1})`;path.unshift(p);n=n.parentElement}return path.join(' > ')}
function getEl(sel=state.selected){try{return sel==='body'?doc().body:doc().querySelector(sel)}catch{return null}}
function currentRec(){if(!state.selected)return null;state.styles[state.selected]||={desktop:{},tablet:{},mobile:{}};return state.styles[state.selected][state.device]||(state.styles[state.selected][state.device]={})}
function merged(sel){const s=state.styles[sel]||{};return Object.assign({},s.desktop||{},state.device==='desktop'?{}:(s[state.device]||{}))}
function applyOne(el,r,sel){if(!el||!r)return;if(r.text!==undefined){if(/INPUT|TEXTAREA/.test(el.tagName))el.value=r.text;else el.textContent=r.text}if(r.href!==undefined&&el.matches('a'))el.href=r.href||'#';if(r.src!==undefined&&el.matches('img,video,source'))el.src=r.src||'';el.style.color=r.color||'';el.style.backgroundColor=r.backgroundColor||'';el.style.fontSize=r.fontSize?`${r.fontSize}px`:'';el.style.borderRadius=r.radius?`${r.radius}px`:'';el.style.padding=r.padding!==''&&r.padding!=null?`${r.padding}px`:'';el.style.margin=r.margin!==''&&r.margin!=null?`${r.margin}px`:'';el.style.textAlign=r.textAlign||'';el.style.display=r.display||'';el.style.width=r.widthMode==='full'?'100%':r.widthMode==='custom'&&r.width?`${r.width}px`:'';el.style.height=r.heightMode==='full'?'100%':r.heightMode==='custom'&&r.height?`${r.height}px`:'';el.style.maxWidth=r.widthMode==='auto'?'100%':'';el.style.boxSizing='border-box';if(r.hoverBg){el.dataset.pbHoverBg=r.hoverBg;el.classList.add('pb-editor-hoverable')}else{delete el.dataset.pbHoverBg;el.classList.remove('pb-editor-hoverable')}}
function applyAll(){const d=doc();if(!d)return;state.deleted.forEach(sel=>{const n=getEl(sel);if(n)n.style.display='none'});state.custom.forEach(c=>{if(!d.querySelector(`[data-pb-key="${esc(c.key)}"]`)){const parent=c.parent?d.querySelector(c.parent):d.body;const n=d.createElement(c.tag);n.dataset.pbKey=c.key;n.innerHTML=c.html||'';if(c.className)n.className=c.className;(parent||d.body).appendChild(n)}});Object.keys(state.styles).forEach(sel=>{const el=getEl(sel);applyOne(el,merged(sel),sel)});installHoverStyle()}
function installHoverStyle(){const d=doc();let st=d.getElementById('pb-editor-hover-style');if(!st){st=d.createElement('style');st.id='pb-editor-hover-style';st.textContent='.pb-editor-hoverable:hover{background-color:var(--pb-hover)!important}';d.head.appendChild(st)}d.querySelectorAll('[data-pb-hover-bg]').forEach(n=>n.style.setProperty('--pb-hover',n.dataset.pbHoverBg))}
function select(el){doc().querySelectorAll('.pb-editor-selected').forEach(n=>n.classList.remove('pb-editor-selected'));state.selected=selector(el);el.classList.add('pb-editor-selected');renderInspector();renderLayers()}
function renderInspector(){const el=getEl();$('selectedName').textContent=state.selected||'Click an element';const r=currentRec()||{};$('textValue').value=r.text??(el?( /INPUT|TEXTAREA/.test(el.tagName)?el.value:el.textContent.trim()):'');$('hrefValue').value=r.href??(el?.getAttribute('href')||'');$('srcValue').value=r.src??(el?.getAttribute('src')||'');$('colorValue').value=r.color||rgbToHex(el?getComputedStyle(el).color:'')||'#222222';$('bgValue').value=r.backgroundColor||rgbToHex(el?getComputedStyle(el).backgroundColor:'')||'#ffffff';$('fontSizeValue').value=r.fontSize??'';$('radiusValue').value=r.radius??'';$('widthMode').value=r.widthMode||'auto';$('widthValue').value=r.width??'';$('heightMode').value=r.heightMode||'auto';$('heightValue').value=r.height??'';$('paddingValue').value=r.padding??'';$('marginValue').value=r.margin??'';$('alignValue').value=r.textAlign||'';$('displayValue').value=r.display||'';$('hoverEnabled').checked=!!r.hoverBg;$('hoverBgValue').value=r.hoverBg||'#0f766e'}
function rgbToHex(v){const m=String(v).match(/\d+/g);if(!m||m.length<3)return'';return'#'+m.slice(0,3).map(x=>(+x).toString(16).padStart(2,'0')).join('')}
function snapshot(){state.history.push(JSON.stringify({styles:state.styles,custom:state.custom,deleted:state.deleted}));if(state.history.length>50)state.history.shift();state.future=[]}
function mutate(fn){snapshot();fn();applyAll();renderInspector();renderLayers()}
function bindFields(){const map={textValue:'text',hrefValue:'href',srcValue:'src',colorValue:'color',bgValue:'backgroundColor',fontSizeValue:'fontSize',radiusValue:'radius',widthMode:'widthMode',widthValue:'width',heightMode:'heightMode',heightValue:'height',paddingValue:'padding',marginValue:'margin',alignValue:'textAlign',displayValue:'display',hoverBgValue:'hoverBg'};Object.entries(map).forEach(([id,key])=>$(id).addEventListener('input',()=>{const r=currentRec();if(!r)return;if(key==='hoverBg'&&!$('hoverEnabled').checked)return;r[key]=['fontSize','radius','width','height','padding','margin'].includes(key)?($ (id).value===''?'':Number($(id).value)):$(id).value;applyAll()}));$('hoverEnabled').addEventListener('change',()=>{const r=currentRec();if(!r)return;r.hoverBg=$('hoverEnabled').checked?$('hoverBgValue').value:'';applyAll()})}
function renderLayers(){const d=doc(),box=$('layers');if(!d)return;const nodes=[...d.body.querySelectorAll('header,main,section,footer,h1,h2,h3,p,a,button,img')].slice(0,120);box.innerHTML='';nodes.forEach(n=>{const b=document.createElement('button');b.className='layer'+(selector(n)===state.selected?' active':'');b.textContent=`${n.tagName.toLowerCase()} — ${(n.textContent||n.alt||n.id||n.className||'').trim().slice(0,38)}`;b.onclick=()=>select(n);box.appendChild(b)})}
function installEditor(){const d=doc();if(!d)return;let st=d.getElementById('pb-editor-style');if(!st){st=d.createElement('style');st.id='pb-editor-style';st.textContent='*{box-sizing:border-box}.pb-editor-mode *{cursor:pointer!important}.pb-editor-selected{outline:3px solid #00a78e!important;outline-offset:2px!important}';d.head.appendChild(st)}d.body.classList.add('pb-editor-mode');d.addEventListener('click',e=>{if(e.target.closest('[data-pb-ignore]'))return;e.preventDefault();e.stopPropagation();select(e.target)},true);d.addEventListener('submit',e=>e.preventDefault(),true);applyAll();renderLayers();autoHeight()}
function autoHeight(){const d=doc();if(!d)return;const h=Math.max(d.documentElement.scrollHeight,d.body.scrollHeight,700);frame.style.height=h+'px'}
async function loadData(){status('Loading…');state.styles={};state.custom=[];state.deleted=[];state.recordId='';try{const r=await fetch(`${API}/api/admin/page-sections?page=${encodeURIComponent(state.page)}`,{headers:headers()});const a=await r.json();if(!r.ok)throw new Error(a.error||'Load failed');const rec=(Array.isArray(a)?a:[]).find(x=>x.sectionKey==='__page_builder__');if(rec){state.recordId=rec.id||'';let s=rec.settings;try{s=typeof s==='string'?JSON.parse(s):s}catch{s={}}state.styles=s?.elementStyles||{};state.custom=s?.customElements||[];state.deleted=s?.deletedElements||[]}status('Loaded','ok')}catch(e){status('API load failed — editor still opens','error')}loadFrame()}
function loadFrame(){frame.src=(PAGES[state.page]||PAGES.home)+`?builder=${Date.now()}`}
async function save(){status('Saving…');const payload={id:state.recordId,page:state.page,sectionKey:'__page_builder__',sectionType:'builder',title:'Visual Builder Data',subtitle:'',content:'',buttonText:'',buttonUrl:'',mediaUrl:'',backgroundType:'color',backgroundColor:'',backgroundImage:'',textColor:'',headingColor:'',buttonColor:'',fontFamily:'',fontSize:'',sortOrder:9999,active:true,settings:{elementStyles:state.styles,customElements:state.custom,deletedElements:state.deleted}};try{const r=await fetch(`${API}/api/admin/page-sections`,{method:'POST',headers:headers(),body:JSON.stringify(payload)});const o=await r.json().catch(()=>({}));if(!r.ok)throw new Error(o.error||'Save failed');state.recordId=o.id||state.recordId;status('Saved & published','ok')}catch(e){status(e.message,'error');alert('Save failed: '+e.message+'\nCheck admin token and Worker endpoint.')}}
function add(type){const d=doc();if(!d)return;snapshot();const key='pb-'+Date.now();const parent=getEl()?.closest('section,main,body')||d.body;const parentSel=selector(parent);let tag='div',html='';if(type==='section'){tag='section';html='<div style="max-width:1200px;margin:auto;padding:48px 20px"><h2>New Section</h2><p>New section content</p></div>'}if(type==='heading'){tag='h2';html='New Heading'}if(type==='text'){tag='p';html='New text'}if(type==='button'){tag='a';html='New Button'}if(type==='image'){tag='img';html=''}if(type==='spacer'){tag='div';html=''}state.custom.push({key,parent:parentSel,tag,html});state.styles[`[data-pb-key="${key}"]`]={desktop:{widthMode:type==='section'?'full':'auto',heightMode:'auto',padding:type==='button'?12:type==='spacer'?30:'',backgroundColor:type==='button'?'#087f72':'',color:type==='button'?'#ffffff':'',href:type==='button'?'#':'',src:type==='image'?'logo.png':''},tablet:{},mobile:{}};applyAll();const n=d.querySelector(`[data-pb-key="${esc(key)}"]`);if(type==='button')n.href='#';if(type==='image'){n.src='../../logo.png';n.alt='New image';n.style.maxWidth='100%'}select(n);autoHeight()}
function undo(){if(!state.history.length)return;state.future.push(JSON.stringify({styles:state.styles,custom:state.custom,deleted:state.deleted}));const s=JSON.parse(state.history.pop());Object.assign(state,s);applyAll();renderLayers()}
function redo(){if(!state.future.length)return;state.history.push(JSON.stringify({styles:state.styles,custom:state.custom,deleted:state.deleted}));const s=JSON.parse(state.future.pop());Object.assign(state,s);applyAll();renderLayers()}
frame.addEventListener('load',()=>{installEditor();setTimeout(autoHeight,500)});$('pageSelect').addEventListener('change',e=>{state.page=e.target.value;state.selected='';loadData()});document.querySelectorAll('[data-device]').forEach(b=>b.onclick=()=>{state.device=b.dataset.device;document.querySelectorAll('[data-device]').forEach(x=>x.classList.toggle('active',x===b));$('frameShell').className='frame-shell '+state.device;applyAll();renderInspector()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));$('saveBtn').onclick=save;$('openBtn').onclick=()=>window.open(PAGES[state.page],'_blank');$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('duplicateBtn').onclick=()=>{const el=getEl();if(!el)return;const c=el.cloneNode(true);c.dataset.pbKey='pb-'+Date.now();el.after(c);state.custom.push({key:c.dataset.pbKey,parent:selector(el.parentElement),tag:c.tagName.toLowerCase(),html:c.innerHTML,className:c.className.replace('pb-editor-selected','')});select(c);autoHeight()};$('deleteBtn').onclick=()=>{if(!state.selected)return;mutate(()=>{state.deleted.push(state.selected);const e=getEl();if(e)e.style.display='none'});state.selected=''};bindFields();loadData();
})();
