const CEYBREEZ_API_BASE="https://ceybreez-contact-api.ceybreez.workers.dev";
document.addEventListener("DOMContentLoaded",()=>loadCeyBreezBuilder(document.body.dataset.page||"home"));
async function loadCeyBreezBuilder(page){try{const r=await fetch(`${CEYBREEZ_API_BASE}/api/page-sections?page=${encodeURIComponent(page)}`);const rows=await r.json();if(!r.ok)throw new Error(rows.error||'Page content load failed');(Array.isArray(rows)?rows:[]).forEach(applyLegacySection);const rec=(Array.isArray(rows)?rows:[]).find(x=>x.sectionKey==='__page_builder__');if(rec)applyVisualBuilder(settingsOf(rec.settings));document.body.classList.add('cms-ready')}catch(e){console.error('Page Builder load failed',e)}}
function settingsOf(v){try{return typeof v==='string'?JSON.parse(v||'{}'):(v||{})}catch{return{}}}
function device(){return innerWidth<=600?'mobile':innerWidth<=900?'tablet':'desktop'}
function mergeDevice(by){const d=device();return Object.assign({},by?.desktop||{},d==='desktop'?{}:(by?.[d]||{}))}
function applyVisualBuilder(s){const styles=s.elementStyles||{};(s.customElements||[]).forEach(c=>{if(document.querySelector(`[data-pb-key="${CSS.escape(c.key)}"]`))return;let p;try{p=c.parent?document.querySelector(c.parent):document.body}catch{p=document.body}const n=document.createElement(c.tag||'div');n.dataset.pbKey=c.key;n.innerHTML=c.html||'';if(c.className)n.className=c.className;(p||document.body).appendChild(n)});(s.deletedElements||[]).forEach(sel=>{try{const n=document.querySelector(sel);if(n)n.style.display='none'}catch{}});Object.entries(styles).forEach(([sel,by])=>{let n;try{n=sel==='body'?document.body:document.querySelector(sel)}catch{return}applyVisualRecord(n,mergeDevice(by))});installBuilderHover()}
function applyVisualRecord(el,r){if(!el||!r)return;if(r.text!==undefined){if(/INPUT|TEXTAREA/.test(el.tagName))el.value=r.text;else el.textContent=r.text}if(r.href!==undefined&&el.matches('a'))el.href=r.href||'#';if(r.src!==undefined&&el.matches('img,video,source'))el.src=r.src||'';el.style.color=r.color||'';el.style.backgroundColor=r.backgroundColor||'';el.style.fontSize=r.fontSize?`${r.fontSize}px`:'';el.style.borderRadius=r.radius?`${r.radius}px`:'';el.style.padding=r.padding!==''&&r.padding!=null?`${r.padding}px`:'';el.style.margin=r.margin!==''&&r.margin!=null?`${r.margin}px`:'';el.style.textAlign=r.textAlign||'';el.style.display=r.display||'';el.style.width=r.widthMode==='full'?'100%':r.widthMode==='custom'&&r.width?`${r.width}px`:'';el.style.height=r.heightMode==='full'?'100%':r.heightMode==='custom'&&r.height?`${r.height}px`:'';if(r.widthMode==='auto'){el.style.width='';el.style.maxWidth='100%'}el.style.boxSizing='border-box';if(r.hoverBg){el.dataset.pbHoverBg=r.hoverBg;el.classList.add('pb-live-hoverable')}}
function installBuilderHover(){let st=document.getElementById('pb-live-hover-style');if(!st){st=document.createElement('style');st.id='pb-live-hover-style';st.textContent='.pb-live-hoverable:hover{background-color:var(--pb-hover)!important}';document.head.appendChild(st)}document.querySelectorAll('[data-pb-hover-bg]').forEach(n=>n.style.setProperty('--pb-hover',n.dataset.pbHoverBg))}
function applyLegacySection(section){if(section.sectionKey==='__page_builder__')return;const target=document.querySelector(`[data-section="${CSS.escape(section.sectionKey||'')}"]`);if(!target)return;const s=settingsOf(section.settings);const set=(f,v)=>{if(v===undefined||v===null||v==='')return;const n=target.querySelector(`[data-field="${f}"]`);if(n)n.textContent=v};set('title',section.title);set('subtitle',section.subtitle);set('content',section.content);const b=target.querySelector('[data-field="button"]');if(b){if(section.buttonText)b.textContent=section.buttonText;if(section.buttonUrl)b.href=section.buttonUrl}const i=target.querySelector('[data-field="image"]');if(i&&section.mediaUrl)i.src=section.mediaUrl;if(section.backgroundImage){const o=Number(s.overlay??35)/100;target.style.backgroundImage=`linear-gradient(rgba(0,0,0,${o}),rgba(0,0,0,${o})),url('${section.backgroundImage}')`;target.style.backgroundSize=s.backgroundSize||'cover';target.style.backgroundPosition=s.backgroundPosition||'center'}else if(section.backgroundColor)target.style.backgroundColor=section.backgroundColor;if(section.textColor)target.style.color=section.textColor}
let pbResizeTimer;addEventListener('resize',()=>{clearTimeout(pbResizeTimer);pbResizeTimer=setTimeout(()=>loadCeyBreezBuilder(document.body.dataset.page||'home'),180)});
