const CEYBREEZ_API_BASE = "https://ceybreez-contact-api.ceybreez.workers.dev";
document.addEventListener("DOMContentLoaded",()=>loadCeyBreezSections(document.body.dataset.page||"home"));
async function loadCeyBreezSections(page){try{const r=await fetch(`${CEYBREEZ_API_BASE}/api/page-sections?page=${page}`);const sections=await r.json();if(!r.ok)throw new Error(sections.error||'Page content load failed');sections.forEach(applySection);document.body.classList.add('cms-ready')}catch(e){console.error('Page Builder load failed',e)}}
function settingsOf(v){try{return typeof v==='string'?JSON.parse(v||'{}'):(v||{})}catch{return{}}}
function applySection(section){const target=section.sectionKey==='__visual_global'?document.body:document.querySelector(`[data-section="${CSS.escape(section.sectionKey||'')}"]`);if(!target)return;const s=settingsOf(section.settings),mode=s.backgroundMode||section.backgroundType||'color';const set=(field,value)=>{if(value===undefined||value===null||value==='')return;const n=target.querySelector(`[data-field="${field}"]`);if(n)n.textContent=value};set('title',section.title);set('subtitle',section.subtitle);set('content',section.content);const btn=target.querySelector('[data-field="button"]');if(btn){if(section.buttonText)btn.textContent=section.buttonText;if(section.buttonUrl)btn.href=section.buttonUrl}const img=target.querySelector('[data-field="image"]');if(img&&section.mediaUrl)img.src=section.mediaUrl;target.querySelector(':scope > .cms-bg-video')?.remove();if(mode==='video'&&s.videoUrl)applyVideoBackground(target,s.videoUrl);if(Array.isArray(s.cards))renderCards(target,s.cards);applySectionStyles(target,section,s);renderCustom(target,section,s);applyElementStyles(target,s.elementStyles||{});applyVisualBuilderRecords(target,s.visualBuilderRecords||[])}
function applySectionStyles(t,section,s){const mode=s.backgroundMode||section.backgroundType||'color';t.style.background='';t.style.backgroundImage='';if(mode==='image'&&section.backgroundImage){const o=Number(s.overlay??35)/100;t.style.backgroundImage=`linear-gradient(rgba(0,0,0,${o}),rgba(0,0,0,${o})),url('${section.backgroundImage}')`;t.style.backgroundSize=s.backgroundSize||'cover';t.style.backgroundPosition=s.backgroundPosition||'center center'}else if(mode==='gradient')t.style.background=`linear-gradient(135deg,${s.gradientStart||'#ffffff'},${s.gradientEnd||'#f8f3eb'})`;else if(mode==='color'&&section.backgroundColor)t.style.background=section.backgroundColor;if(section.textColor)t.style.color=section.textColor;if(section.fontFamily)t.style.fontFamily=section.fontFamily;if(section.fontSize||s.fontSize)t.style.fontSize=section.fontSize||s.fontSize;if(s.paddingTop)t.style.paddingTop=s.paddingTop;if(s.paddingBottom)t.style.paddingBottom=s.paddingBottom;if(s.borderRadius)t.style.borderRadius=s.borderRadius;t.querySelectorAll('h1,h2,h3').forEach(h=>{if(section.headingColor||s.headingColor)h.style.color=section.headingColor||s.headingColor;if(s.headingFont)h.style.fontFamily=s.headingFont;if(s.headingSize)h.style.fontSize=s.headingSize});if(section.buttonColor)t.querySelectorAll('a,button').forEach(b=>b.style.background=section.buttonColor)}
function device(){return innerWidth<=600?'mobile':innerWidth<=900?'tablet':'desktop'}
function merged(by){const d=device();return Object.assign({},by?.desktop||{},d!=='desktop'?(by?.[d]||{}):{})}
function applyRecord(el,r){if(!el||!r)return;if(r.text!==undefined){if(['INPUT','TEXTAREA'].includes(el.tagName))el.value=r.text;else el.textContent=r.text}if(r.href!==undefined&&el.matches('a,button'))el.setAttribute('href',r.href||'#');if(r.src!==undefined&&el.matches('img,video,source'))el.setAttribute('src',r.src||'');['fontSize','width','height','marginTop','marginRight','marginBottom','marginLeft','paddingTop','paddingRight','paddingBottom','paddingLeft','borderRadius'].forEach(k=>el.style[k]=r[k]===''||r[k]==null?'':`${Number(r[k])}px`);['color','backgroundColor','fontWeight','textAlign'].forEach(k=>el.style[k]=r[k]||'');el.style.opacity=r.opacity===''||r.opacity==null?'':String(r.opacity);el.style.display=r.hidden?'none':'';el.style.transform=`translate(${Number(r.x)||0}px,${Number(r.y)||0}px)`}
function applyElementStyles(section,styles){Object.entries(styles).forEach(([selector,by])=>{let nodes=[];try{nodes=selector===':scope'?[section]:[...section.querySelectorAll(selector)]}catch{return}const r=merged(by);nodes.forEach(n=>applyRecord(n,r))})}
function renderCustom(target,section,s){target.querySelectorAll('[data-pb-custom="1"]').forEach(n=>n.remove());(s.customElements||[]).filter(x=>x.sectionKey===section.sectionKey).forEach(item=>{let n;if(item.type==='button'){n=document.createElement('a');n.href=item.url||'#';n.textContent=item.text||'Button';n.className='cms-custom-button'}else if(item.type==='image'){n=document.createElement('img');n.src=item.url||'';n.alt=item.alt||'';n.className='cms-custom-image'}else{n=document.createElement(item.type==='heading'?'h2':'p');n.textContent=item.text||'';n.className='cms-custom-text'}n.dataset.pbCustom='1';n.dataset.pbId=item.id;target.appendChild(n)})}
function applyVideoBackground(t,url){let v=t.querySelector('.cms-bg-video');if(!v){v=document.createElement('video');v.className='cms-bg-video';v.autoplay=true;v.muted=true;v.loop=true;v.playsInline=true;t.prepend(v)}v.src=url}
function renderCards(t,cards){const box=t.querySelector('[data-field="cards"]');if(!box)return;box.innerHTML='';cards.forEach(c=>{const d=document.createElement('div');d.className='cms-card';if(c.image){const i=document.createElement('img');i.src=c.image;i.alt=c.title||'';d.appendChild(i)}const h=document.createElement('h3');h.textContent=c.title||'';d.appendChild(h);const p=document.createElement('p');p.textContent=c.description||'';d.appendChild(p);if(c.buttonText){const a=document.createElement('a');a.href=c.buttonUrl||'#';a.textContent=c.buttonText;d.appendChild(a)}box.appendChild(d)})}
let rt;addEventListener('resize',()=>{clearTimeout(rt);rt=setTimeout(()=>loadCeyBreezSections(document.body.dataset.page||'home'),180)})


function applyVisualBuilderRecords(root,records){
 const d=device();
 (Array.isArray(records)?records:[]).forEach(r=>{let nodes=[];try{nodes=r.selector===':scope'?[root]:[...root.querySelectorAll(r.selector)]}catch{return}nodes.forEach(el=>{
  if(r.html!==undefined&&r.html!==null&&!['IMG','VIDEO','INPUT','TEXTAREA'].includes(el.tagName))el.innerHTML=r.html;
  Object.entries(r.attrs||{}).forEach(([k,v])=>{if(!k.startsWith('data-cb-'))el.setAttribute(k,v)});
  if(r.style!==undefined)el.setAttribute('style',r.style||'');
  const override=d==='desktop'?{}:(r.deviceStyles?.[d]||{});Object.entries(override).forEach(([k,v])=>{if(v===''||v==null)el.style.removeProperty(k);else el.style.setProperty(k,String(v),'important')});
 })})
}
