
(function(){
const API="https://ceybreez-contact-api.ceybreez.workers.dev",TOKEN_KEY="CEYBREEZ_ADMIN_TOKEN";
const tabs={dashboardTab:["Dashboard","Live CeyBreez operations overview"],inquiriesTab:["Property Inquiry","Inquiry Management"],bookingsTab:["Property Booking Management","Booking Management"],properties:["Properties CMS","Manage villas, apartments and homestays"],destinations:["Tours CMS","Manage tours and destinations"],services:["Cafe & Services CMS","Manage cafes and services"],reviewsTab:["Reviews","Guest reviews management"],reportsTab:["Reports","Revenue, booking and inquiry performance"],pageControl:["Page Builder","Website content and sections"],settingsTab:["Settings","Business settings and integrations"]};
const resolve={properties:"propertiesTab",destinations:"destinationsTab",services:"servicesTab",pageControl:"pageControlTab"};
function authHeaders(){return {"Content-Type":"application/json","Authorization":`Bearer ${localStorage.getItem(TOKEN_KEY)||""}`}}
async function apiGet(path){const res=await fetch(`${API}${path}`,{headers:authHeaders()});const data=await res.json().catch(()=>[]);if(!res.ok)throw new Error(data.error||`Failed: ${path}`);return data}
function iso(d){return d.toISOString().slice(0,10)}function addDays(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()+n);return iso(d)}function fmt(v){if(!v)return"-";const d=new Date(String(v).slice(0,10)+"T00:00:00");return isNaN(d)?v:d.toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}function norm(v){return String(v||"").toLowerCase()}function bookingCovers(b,date){const f=String(b.dateFrom||"").slice(0,10),t=String(b.dateTo||"").slice(0,10);return f&&t&&f<=date&&date<t}function setText(id,v){const el=document.getElementById(id);if(el)el.textContent=v}function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function listHtml(items,kind){if(!items.length)return`<div class="v12-empty">No records</div>`;return items.slice(0,8).map(x=>`<div class="v12-list-item"><div><strong>${esc(x.guestName||x.reference||"Guest")}</strong><small>${esc(x.itemName||x.serviceType||"-")}</small><small>${esc(x.dateFrom||"")} ${x.dateTo?"→ "+esc(x.dateTo):""}</small></div><span class="v12-pill">${esc(kind||x.status||"Open")}</span></div>`).join("")}
async function v12LoadDashboard(){const [inq,bookings,props,tours]=await Promise.all([apiGet('/api/admin/inquiries').catch(()=>[]),apiGet('/api/admin/bookings').catch(()=>[]),apiGet('/api/admin/properties').catch(()=>[]),apiGet('/api/admin/destinations').catch(()=>[])]);const y=addDays(-1),t=addDays(0),tm=addDays(1);const active=bookings.filter(b=>norm(b.status)==='booked');const checkIn=d=>active.filter(b=>String(b.dateFrom||'').slice(0,10)===d);const checkOut=d=>active.filter(b=>String(b.dateTo||'').slice(0,10)===d);const inHouse=active.filter(b=>bookingCovers(b,t));setText('v12NewInquiries',inq.filter(i=>['new','contacted','quoted'].includes(norm(i.status||'New'))).length);setText('v12ActiveBookings',active.length);setText('v12PropertiesCount',props.length);setText('v12ToursCount',tours.length);setText('v12YesterdayIn',checkIn(y).length);setText('v12YesterdayOut',checkOut(y).length);setText('v12TodayIn',checkIn(t).length);setText('v12TodayOut',checkOut(t).length);setText('v12InHouse',inHouse.length);setText('v12TomorrowIn',checkIn(tm).length);setText('v12TomorrowOut',checkOut(tm).length);let yl=document.getElementById('v12YesterdayList'),tl=document.getElementById('v12TodayList'),ml=document.getElementById('v12TomorrowList');if(yl)yl.innerHTML=`<b>${fmt(y)}</b>`+listHtml([...checkIn(y),...checkOut(y)],'Done');if(tl)tl.innerHTML=`<b>${fmt(t)}</b>`+listHtml([...checkIn(t),...checkOut(t),...inHouse],'Today');if(ml)ml.innerHTML=`<b>${fmt(tm)}</b>`+listHtml([...checkIn(tm),...checkOut(tm)],'Tomorrow');let ri=document.getElementById('v12RecentInquiries'),rb=document.getElementById('v12RecentBookings');if(ri)ri.innerHTML=listHtml([...inq].sort((a,b)=>String(b.createdAt||b.created_at||'').localeCompare(String(a.createdAt||a.created_at||''))),'Inquiry');if(rb)rb.innerHTML=listHtml([...bookings].sort((a,b)=>String(b.createdAt||b.created_at||'').localeCompare(String(a.createdAt||a.created_at||''))),'Booking')}
window.v12LoadDashboard=v12LoadDashboard;const originalShowTab=window.showTab;window.showTab=function(tab){const id=resolve[tab]||tab;document.querySelectorAll('.v12-module,#destinationsTab,#propertiesTab,#servicesTab,#inquiriesTab,#bookingsTab,#reviewsTab,#reportsTab,#pageControlTab,#settingsTab').forEach(el=>el.classList.add('hidden'));const target=document.getElementById(id);if(target)target.classList.remove('hidden');document.querySelectorAll('.v12-nav button').forEach(btn=>btn.classList.toggle('active',(resolve[btn.dataset.tab]||btn.dataset.tab)===id));const title=tabs[tab]||tabs[id]||["CeyBreez Admin","Management module"];setText('v12PageTitle',title[0]);setText('v12PageSubtitle',title[1]);window.scrollTo(0,0);document.body.classList.remove('v12-sidebar-open');if(id==='dashboardTab'){v12LoadDashboard();return}if(typeof originalShowTab==='function'){try{originalShowTab(tab)}catch(e){console.warn('V10 showTab warning',e)}document.querySelectorAll('.v12-module,#destinationsTab,#propertiesTab,#servicesTab,#inquiriesTab,#bookingsTab,#reviewsTab,#reportsTab,#pageControlTab,#settingsTab').forEach(el=>el.classList.add('hidden'));const t2=document.getElementById(id);if(t2)t2.classList.remove('hidden')}};
const originalLogin=window.loginAdmin;window.loginAdmin=function(){if(typeof originalLogin==='function')originalLogin();setTimeout(()=>{document.getElementById('v12LoginPage')?.classList.add('hidden');window.showTab('dashboardTab')},150)};const originalLogout=window.logoutAdmin;window.logoutAdmin=function(){if(typeof originalLogout==='function')return originalLogout();localStorage.removeItem(TOKEN_KEY);location.reload()};window.v12RefreshCurrent=function(){const active=document.querySelector('.v12-nav button.active')?.dataset.tab||'dashboardTab';if(active==='dashboardTab')return v12LoadDashboard();if(active==='inquiriesTab'&&typeof loadInquiries==='function')return loadInquiries();if(active==='bookingsTab'&&typeof loadBookings==='function')return loadBookings();if(active==='properties'&&typeof loadProperties==='function')return loadProperties();if(active==='destinations'&&typeof loadDestinations==='function')return loadDestinations();if(active==='services'&&typeof loadServices==='function')return loadServices();location.reload()};
document.addEventListener('DOMContentLoaded',()=>{const hasToken=!!localStorage.getItem(TOKEN_KEY);if(hasToken){document.getElementById('v12LoginPage')?.classList.add('hidden');document.getElementById('loginBox')?.classList.add('hidden');document.getElementById('adminPanel')?.classList.remove('hidden');setTimeout(()=>window.showTab('dashboardTab'),400)}else{document.getElementById('v12LoginPage')?.classList.remove('hidden');document.getElementById('adminPanel')?.classList.add('hidden')}});
})();
