/* =========================
   V7 PROFESSIONAL STABLE CORE
========================= */
function v7Text(item){return `${item?.bookingCategory||""} ${item?.category||""} ${item?.serviceType||""} ${item?.itemName||""} ${item?.reference||""} ${item?.message||""}`.toLowerCase();}
function classifyInquiryItem(item){const t=v7Text(item); if(t.includes('tour')||t.includes('trip')||t.includes('safari')||t.includes('excursion')||t.includes('pickup')||t.includes('guide')||t.includes('round tour'))return 'tour'; if(t.includes('cafe')||t.includes('service')||t.includes('restaurant')||t.includes('contact')||t.includes('taxi')||t.includes('rental'))return 'service'; return 'property';}
function classifyBookingItem(item){const t=v7Text(item); if(t.includes('tour')||t.includes('trip')||t.includes('safari')||t.includes('excursion')||t.includes('pickup')||t.includes('guide')||t.includes('round tour'))return 'tour'; if(String(item?.reference||'').startsWith('MAN-')||String(item?.inquiryId||'').startsWith('MAN-'))return 'manual'; return 'property';}
function v7Bool(v){return v===1||v===true||String(v||'').toLowerCase()==='true'||String(v||'')==='1';}
function v7GuestBadge(i){return v7Bool(i?.guestConfirmed)?`<span class="status-badge status-booked">Guest Confirmed</span>`:`<span class="status-badge status-quoted">Guest Pending</span>`;}
function v7AdminBadge(i){return v7Bool(i?.adminConfirmed)||normalizeStatus(i?.status)==='booked'?`<span class="status-badge status-booked">Admin Confirmed</span>`:`<span class="status-badge status-contacted">Admin Pending</span>`;}
function v7PaymentBadge(i){const s=String(i?.paymentStatus||'Pending'); const cls=s.toLowerCase().includes('paid')?'status-booked':'status-contacted'; return `<span class="status-badge ${cls}">${escapeHtml(s)}</span>`;}
function setInquiryMode(mode,btn){v6InquiryMode=mode||'all'; const h=document.getElementById('v6InquiryMode'); if(h)h.value=v6InquiryMode; document.querySelectorAll('[data-inquiry-mode]').forEach(x=>x.classList.remove('active')); btn?.classList.add('active'); applyInquiryFilters();}
function setBookingMode(mode,btn){v6BookingMode=mode||'all'; const h=document.getElementById('v6BookingMode'); if(h)h.value=v6BookingMode; document.querySelectorAll('[data-booking-mode]').forEach(x=>x.classList.remove('active')); btn?.classList.add('active'); applyBookingFilters();}
function renderDashboardCards(data){const b=document.getElementById('inquiryCards'); if(!b)return; const c=s=>data.filter(x=>normalizeStatus(x.status)===s.toLowerCase()).length; b.innerHTML=`<div class="dashboard-card"><h3>Total Inquiries</h3><div class="value">${data.length}</div></div><div class="dashboard-card"><h3>Property Inquiries</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='property').length}</div></div><div class="dashboard-card"><h3>Tour Inquiries</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='tour').length}</div></div><div class="dashboard-card"><h3>Service / Contact</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='service').length}</div></div><div class="dashboard-card card-new"><h3>New</h3><div class="value">${c('New')}</div></div><div class="dashboard-card card-booked"><h3>Booked</h3><div class="value">${c('Booked')}</div></div><div class="dashboard-card card-closed"><h3>Cancelled / Closed</h3><div class="value">${c('Cancelled')+c('Closed')}</div></div>`;}
function renderInquiryTypeCards(data){const b=document.getElementById('inquiryTypeCards'); if(!b)return; b.innerHTML=`<div class="dashboard-card"><h3>🏡 Properties</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='property').length}</div></div><div class="dashboard-card"><h3>🧭 Tours</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='tour').length}</div></div><div class="dashboard-card"><h3>☕ Services / Contact</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='service').length}</div></div><div class="dashboard-card"><h3>🏡 Villas</h3><div class="value">${data.filter(x=>v7Text(x).includes('villa')).length}</div></div><div class="dashboard-card"><h3>🏢 Apartments</h3><div class="value">${data.filter(x=>v7Text(x).includes('apartment')).length}</div></div><div class="dashboard-card"><h3>🏠 Homestays</h3><div class="value">${data.filter(x=>v7Text(x).includes('homestay')).length}</div></div>`;}
function renderBookingStats(data){const b=document.getElementById('bookingStats'); if(!b)return; const c=s=>data.filter(x=>normalizeStatus(x.status)===s).length; b.innerHTML=`<div class="dashboard-card"><h3>Total Bookings</h3><div class="value">${data.length}</div></div><div class="dashboard-card"><h3>Property Bookings</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='property').length}</div></div><div class="dashboard-card"><h3>Tour Bookings</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='tour').length}</div></div><div class="dashboard-card"><h3>Manual Bookings</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='manual').length}</div></div><div class="dashboard-card card-booked"><h3>Booked</h3><div class="value">${c('booked')}</div></div><div class="dashboard-card card-closed"><h3>Cancelled</h3><div class="value">${c('cancelled')}</div></div>`;}
function applyInquiryFilters(){const ins=document.querySelectorAll('#inquirySearch'); let search=''; ins.forEach(i=>{if(i.value.trim())search=i.value.toLowerCase();}); const old=document.getElementById('inquiryFilter')?.value||''; const ns=document.getElementById('inquiryStatusFilter')?.value||'all'; const mode=v6InquiryMode||document.getElementById('v6InquiryMode')?.value||'all'; let status=''; if(ns&&ns!=='all')status=ns.toLowerCase(); if(old)status=old.toLowerCase(); const filtered=allInquiries.filter(item=>{const txt=`${item.reference||''} ${item.guestName||''} ${item.guestEmail||''} ${item.guestMobile||''} ${item.serviceType||''} ${item.itemName||''} ${item.message||''}`.toLowerCase(); return (mode==='all'||classifyInquiryItem(item)===mode)&&(!status||normalizeStatus(item.status)===status)&&(!search||txt.includes(search));}); renderDashboardCards(allInquiries); renderInquiryTypeCards(allInquiries); renderInquiryTable(filtered); const box=document.getElementById('inquiriesList'); if(box)box.innerHTML='';}
function applyBookingFilters(){const search=(document.getElementById('bookingSearch')?.value||'').toLowerCase(); const status=(document.getElementById('bookingStatusFilter')?.value||'all').toLowerCase(); const type=(document.getElementById('bookingTypeFilter')?.value||'all').toLowerCase(); const mode=v6BookingMode||document.getElementById('v6BookingMode')?.value||'all'; const filtered=allBookings.filter(item=>{const cat=classifyBookingItem(item); const sm=status==='all'||normalizeStatus(item.status)===status; const mm=mode==='all'||cat===mode; const tt=`${item.serviceType||''} ${item.itemName||''} ${item.bookingCategory||''}`.toLowerCase(); const tm=type==='all'||tt.includes(type)||cat===type; const st=`${item.id||''} ${item.reference||''} ${item.itemName||''} ${item.serviceType||''} ${item.guestName||''} ${item.guestEmail||''} ${item.guestMobile||''}`.toLowerCase(); return mm&&sm&&tm&&(!search||st.includes(search));}); renderBookingStats(allBookings); renderBookingsTable(filtered); renderBookingsCalendar(filtered); renderAvailabilityMatrix();}
function renderInquiryTable(data){const tb=document.getElementById('inquiryTableBody'); if(!tb)return; const th=tb.closest('table')?.querySelector('thead tr'); if(th)th.innerHTML='<th>Reference</th><th>Date</th><th>Type</th><th>Property / Tour</th><th>Guest</th><th>Dates</th><th>Guest</th><th>Admin</th><th>Status</th>'; if(!data.length){tb.innerHTML='<tr><td colspan="9" class="empty-row">No inquiries found</td></tr>';return;} tb.innerHTML=data.map(item=>`<tr onclick="openInquiryModal('${escapeJs(item.id)}')" class="clickable-row"><td>${escapeHtml(item.reference||item.id||'-')}</td><td>${formatDate(item.createdAt||item.created_at)}</td><td>${escapeHtml(classifyInquiryItem(item).toUpperCase())}<br><small>${escapeHtml(item.serviceType||'-')}</small></td><td>${escapeHtml(item.itemName||'-')}</td><td><strong>${escapeHtml(item.guestName||'-')}</strong><br><small>${escapeHtml(item.guestEmail||'')}</small></td><td>${escapeHtml(item.dateFrom||'-')} → ${escapeHtml(item.dateTo||(classifyInquiryItem(item)==='tour'?item.dateFrom:'-'))}</td><td>${v7GuestBadge(item)}</td><td>${v7AdminBadge(item)}</td><td><span class="status-badge status-${normalizeStatus(item.status)}">${escapeHtml(item.status||'New')}</span></td></tr>`).join('');}
function renderBookingsTable(data){const tb=document.getElementById('bookingTableBody'); if(!tb)return; const th=tb.closest('table')?.querySelector('thead tr'); if(th)th.innerHTML='<th>Reference</th><th>Created</th><th>Type</th><th>Property / Tour</th><th>Guest</th><th>Dates</th><th>Amount</th><th>Guest</th><th>Payment</th><th>Status</th><th>Action</th>'; if(!data.length){tb.innerHTML='<tr><td colspan="11" class="empty-row">No bookings found</td></tr>';return;} tb.innerHTML=data.map(item=>`<tr onclick="openBookingDetails('${escapeJs(item.id)}')" class="clickable-row"><td>${escapeHtml(item.reference||item.id||'-')}</td><td>${formatDate(item.createdAt||item.created_at)}</td><td>${escapeHtml(classifyBookingItem(item).toUpperCase())}<br><small>${escapeHtml(item.serviceType||'-')}</small></td><td>${escapeHtml(item.itemName||'-')}</td><td><strong>${escapeHtml(item.guestName||'-')}</strong><br><small>${escapeHtml(item.guestEmail||'')}</small><br><small>${escapeHtml(item.guestMobile||'')}</small></td><td>${escapeHtml(item.dateFrom||'-')} → ${escapeHtml(item.dateTo||'-')}</td><td>${escapeHtml(item.currency||item.quoteCurrency||'')} ${escapeHtml(item.totalAmount||item.quoteTotalAmount||'-')}</td><td>${v7GuestBadge(item)}</td><td>${v7PaymentBadge(item)}</td><td><span class="status-badge status-${normalizeStatus(item.status||'Booked')}">${escapeHtml(item.status||'Booked')}</span></td><td onclick="event.stopPropagation();"><button class="mini-btn" onclick="openBookingDetails('${escapeJs(item.id)}')">Manage</button></td></tr>`).join('');}
async function deleteInquiry(id){if(!confirm('Delete this inquiry? Related booking and notes will also be removed.'))return; try{const res=await fetch(`${API_BASE}/api/admin/inquiries/${id}`,{method:'DELETE',headers:authHeaders()}); const result=await res.json(); if(!res.ok)return alert(result.error||'Delete failed'); alert('Inquiry and related records deleted'); closeInquiryModal?.(); await loadInquiries(); await loadBookings();}catch(err){alert(err.message);}}
async function cleanupOrphanBookings(){if(!confirm('Clean orphan bookings that no longer have matching inquiries?'))return; const res=await fetch(`${API_BASE}/api/admin/bookings/cleanup-orphans`,{method:'POST',headers:authHeaders()}); const result=await res.json(); if(!res.ok)return alert(result.error||'Cleanup failed'); alert(`Cleanup completed. Removed ${result.deleted||0} orphan booking(s).`); await loadBookings(); await loadInquiries();}
async function syncBookingsFromInquiries(){const res=await fetch(`${API_BASE}/api/admin/bookings/sync-from-inquiries`,{method:'POST',headers:authHeaders()}); const result=await res.json(); if(!res.ok)return alert(result.error||'Sync failed'); alert('Booking sync completed'); await loadBookings(); await loadInquiries();}
setTimeout(()=>{const tools=document.querySelector('.booking-tools'); if(tools&&!document.getElementById('cleanupOrphansBtn')){const b=document.createElement('button'); b.id='cleanupOrphansBtn'; b.type='button'; b.textContent='Clean Orphans'; b.onclick=cleanupOrphanBookings; tools.appendChild(b);} if(tools&&!document.getElementById('syncBookingsBtn')){const b=document.createElement('button'); b.id='syncBookingsBtn'; b.type='button'; b.textContent='Sync Bookings'; b.onclick=syncBookingsFromInquiries; tools.appendChild(b);}},1200);


