/* =========================
   V9 PROFESSIONAL COMPLETE UI FIX
   Clean one-filter system. Removes duplicate visual tabs/buttons.
========================= */
let v9InquiryFilter = "all";
let v9BookingFilter = "all";
function v9Text(item){return `${item?.bookingCategory||""} ${item?.category||""} ${item?.serviceType||""} ${item?.itemName||""} ${item?.reference||""} ${item?.message||""}`.toLowerCase();}
function classifyInquiryItem(item){const t=v9Text(item); if(t.includes('tour')||t.includes('trip')||t.includes('safari')||t.includes('excursion')||t.includes('pickup')||t.includes('guide')||t.includes('round tour')) return 'tour'; if(t.includes('cafe')||t.includes('service')||t.includes('restaurant')||t.includes('contact')||t.includes('taxi')||t.includes('rental')) return 'service'; return 'property';}
function classifyBookingItem(item){const t=v9Text(item); if(t.includes('tour')||t.includes('trip')||t.includes('safari')||t.includes('excursion')||t.includes('pickup')||t.includes('guide')||t.includes('round tour')) return 'tour'; if(String(item?.reference||'').startsWith('MAN-')||String(item?.inquiryId||'').startsWith('MAN-')) return 'manual'; return 'property';}
function v9Bool(v){return v===1||v===true||String(v||'').toLowerCase()==='true'||String(v||'')==='1';}
function v9GuestBadge(item){return v9Bool(item?.guestConfirmed)?`<span class="status-badge status-booked">Guest Confirmed</span>`:`<span class="status-badge status-quoted">Guest Pending</span>`;}
function v9AdminBadge(item){return v9Bool(item?.adminConfirmed)||normalizeStatus(item?.status)==='booked'?`<span class="status-badge status-booked">Admin Confirmed</span>`:`<span class="status-badge status-contacted">Admin Pending</span>`;}
function v9PaymentBadge(item){const s=String(item?.paymentStatus||'Pending'); const cls=s.toLowerCase().includes('paid')?'status-booked':'status-contacted'; return `<span class="status-badge ${cls}">${escapeHtml(s)}</span>`;}
function getItemNameForBooking(inquiry){let item=inquiry?.itemName||''; if(!item){item=String(inquiry?.serviceType||'').replace('Villa Inquiry - ','').replace('Apartment Inquiry - ','').replace('Homestay Inquiry - ','').replace('Tour Inquiry - ','').replace('Tours Inquiry - ','').trim();} return item||'CeyBreez Booking';}
function v9RemoveDuplicateControls(){
  document.querySelectorAll('.v6-mode-tabs').forEach(x=>x.remove());
  document.querySelectorAll('button').forEach(btn=>{const t=(btn.textContent||'').trim().toLowerCase(); if(t==='property bookings'||t==='tour bookings'||t==='property inquiry'||t==='tour inquiry'||t==='property inquiries'||t==='tour inquiries'){btn.remove();}});
  const inq=[]; document.querySelectorAll('#inquiriesTab select').forEach(sel=>{if((sel.textContent||'').toLowerCase().includes('all inquiry types'))inq.push(sel);}); inq.slice(1).forEach(x=>x.remove());
  const bok=[]; document.querySelectorAll('#bookingsTab select, .booking-tools select').forEach(sel=>{if((sel.textContent||'').toLowerCase().includes('all booking types'))bok.push(sel);}); bok.slice(1).forEach(x=>x.remove());
  const clean=[]; const sync=[]; document.querySelectorAll('button').forEach(btn=>{const t=(btn.textContent||'').trim().toLowerCase(); if(t==='clean orphans') clean.push(btn); if(t==='sync bookings') sync.push(btn);}); clean.slice(1).forEach(x=>x.remove()); sync.slice(1).forEach(x=>x.remove());
}
function v9InjectFilters(){
  const inquiryTools=document.querySelector('#inquiriesTab .inquiry-tools');
  if(inquiryTools&&!document.getElementById('v9InquiryFilter')){const s=document.createElement('select'); s.id='v9InquiryFilter'; s.innerHTML=`<option value="all">All Inquiry Types</option><option value="property">Property Only</option><option value="tour">Tour Only</option><option value="service">Cafe / Service Only</option>`; s.onchange=()=>{v9InquiryFilter=s.value||'all'; applyInquiryFilters();}; inquiryTools.prepend(s);}
  const bookingTools=document.querySelector('.booking-tools');
  if(bookingTools&&!document.getElementById('v9BookingFilter')){const s=document.createElement('select'); s.id='v9BookingFilter'; s.innerHTML=`<option value="all">All Booking Types</option><option value="property">Property Only</option><option value="tour">Tour Only</option><option value="manual">Manual Only</option>`; s.onchange=()=>{v9BookingFilter=s.value||'all'; applyBookingFilters();}; bookingTools.prepend(s); const c=document.createElement('button'); c.id='v9CleanBtn'; c.type='button'; c.textContent='Clean Orphans'; c.onclick=cleanupOrphanBookings; bookingTools.appendChild(c); const y=document.createElement('button'); y.id='v9SyncBtn'; y.type='button'; y.textContent='Sync Bookings'; y.onclick=syncBookingsFromInquiries; bookingTools.appendChild(y);}
  v9RemoveDuplicateControls();
}
function setInquiryMode(mode,btn){v9InquiryFilter=mode||'all'; const s=document.getElementById('v9InquiryFilter'); if(s)s.value=v9InquiryFilter; applyInquiryFilters();}
function setBookingMode(mode,btn){v9BookingFilter=mode||'all'; const s=document.getElementById('v9BookingFilter'); if(s)s.value=v9BookingFilter; applyBookingFilters();}
function renderDashboardCards(data){const box=document.getElementById('inquiryCards'); if(!box)return; const c=status=>data.filter(x=>normalizeStatus(x.status)===status.toLowerCase()).length; box.innerHTML=`<div class="dashboard-card"><h3>Total Inquiries</h3><div class="value">${data.length}</div></div><div class="dashboard-card"><h3>Property</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='property').length}</div></div><div class="dashboard-card"><h3>Tour</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='tour').length}</div></div><div class="dashboard-card"><h3>Service</h3><div class="value">${data.filter(x=>classifyInquiryItem(x)==='service').length}</div></div><div class="dashboard-card card-new"><h3>New</h3><div class="value">${c('New')}</div></div><div class="dashboard-card card-booked"><h3>Booked</h3><div class="value">${c('Booked')}</div></div><div class="dashboard-card card-closed"><h3>Cancelled / Closed</h3><div class="value">${c('Cancelled')+c('Closed')}</div></div>`;}
function renderBookingStats(data){const box=document.getElementById('bookingStats'); if(!box)return; const c=status=>data.filter(x=>normalizeStatus(x.status)===status).length; box.innerHTML=`<div class="dashboard-card"><h3>Total Bookings</h3><div class="value">${data.length}</div></div><div class="dashboard-card"><h3>Property</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='property').length}</div></div><div class="dashboard-card"><h3>Tour</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='tour').length}</div></div><div class="dashboard-card"><h3>Manual</h3><div class="value">${data.filter(x=>classifyBookingItem(x)==='manual').length}</div></div><div class="dashboard-card card-booked"><h3>Booked</h3><div class="value">${c('booked')}</div></div><div class="dashboard-card card-closed"><h3>Cancelled</h3><div class="value">${c('cancelled')}</div></div>`;}
function applyInquiryFilters(){v9InjectFilters(); let search=''; document.querySelectorAll('#inquirySearch').forEach(input=>{if(input.value.trim())search=input.value.toLowerCase();}); const oldStatus=document.getElementById('inquiryFilter')?.value||''; const newStatus=document.getElementById('inquiryStatusFilter')?.value||'all'; const category=document.getElementById('v9InquiryFilter')?.value||v9InquiryFilter||'all'; let status=''; if(newStatus&&newStatus!=='all')status=newStatus.toLowerCase(); if(oldStatus)status=oldStatus.toLowerCase(); const filtered=allInquiries.filter(item=>{const text=`${item.reference||''} ${item.guestName||''} ${item.guestEmail||''} ${item.guestMobile||''} ${item.serviceType||''} ${item.itemName||''} ${item.message||''}`.toLowerCase(); return (category==='all'||classifyInquiryItem(item)===category)&&(!status||normalizeStatus(item.status)===status)&&(!search||text.includes(search));}); renderDashboardCards(allInquiries); if(typeof renderInquiryTypeCards==='function')renderInquiryTypeCards(allInquiries); renderInquiryTable(filtered); const box=document.getElementById('inquiriesList'); if(box)box.innerHTML=''; v9RemoveDuplicateControls();}
function applyBookingFilters(){v9InjectFilters(); const search=(document.getElementById('bookingSearch')?.value||'').toLowerCase(); const status=(document.getElementById('bookingStatusFilter')?.value||'all').toLowerCase(); const type=(document.getElementById('bookingTypeFilter')?.value||'all').toLowerCase(); const category=document.getElementById('v9BookingFilter')?.value||v9BookingFilter||'all'; const filtered=allBookings.filter(item=>{const cat=classifyBookingItem(item); const typeText=`${item.serviceType||''} ${item.itemName||''} ${item.bookingCategory||''}`.toLowerCase(); const searchText=`${item.id||''} ${item.reference||''} ${item.itemName||''} ${item.serviceType||''} ${item.guestName||''} ${item.guestEmail||''} ${item.guestMobile||''}`.toLowerCase(); return (category==='all'||cat===category)&&(status==='all'||normalizeStatus(item.status)===status)&&(type==='all'||typeText.includes(type)||cat===type)&&(!search||searchText.includes(search));}); renderBookingStats(allBookings); renderBookingsTable(filtered); renderBookingsCalendar(filtered); renderAvailabilityMatrix(); v9RemoveDuplicateControls();}
async function cleanupOrphanBookings(){if(!confirm('Clean orphan bookings?'))return; const res=await fetch(`${API_BASE}/api/admin/bookings/cleanup-orphans`,{method:'POST',headers:authHeaders()}); const result=await res.json(); if(!res.ok)return alert(result.error||'Cleanup failed'); alert(`Removed ${result.deleted||0} orphan booking(s).`); await loadBookings(); await loadInquiries();}
async function syncBookingsFromInquiries(){const res=await fetch(`${API_BASE}/api/admin/bookings/sync-from-inquiries`,{method:'POST',headers:authHeaders()}); const result=await res.json(); if(!res.ok)return alert(result.error||'Sync failed'); alert('Booking sync completed'); await loadBookings(); await loadInquiries();}
function v9PaymentPayload(){return {currency:document.getElementById('bookingConfirmCurrency')?.value||'USD',unitRate:document.getElementById('bookingConfirmDayRate')?.value||'',discountPercent:document.getElementById('quoteDiscountPercent')?.value||'0',discountAmount:document.getElementById('quoteDiscountAmount')?.value||'0',totalAmount:document.getElementById('bookingConfirmTotalAmount')?.value||'',validUntil:document.getElementById('quoteValidUntil')?.value||'',paymentStatus:document.getElementById('quotePaymentStatus')?.value||'Pending',advanceAmount:document.getElementById('quoteAdvanceAmount')?.value||'',balanceAmount:document.getElementById('quoteBalanceAmount')?.value||'',adminMessage:document.getElementById('bookingConfirmAdminMessage')?.value||''};}
async function savePaymentStatus(sendEmail=false){const id=currentInquiry?.id; if(!id)return alert('Inquiry not selected'); if(!confirm(sendEmail?'Save payment and send invoice/payment email to guest?':'Save payment status and sync with booking?'))return; const payload=v9PaymentPayload(); payload.sendEmail=!!sendEmail; const res=await fetch(`${API_BASE}/api/admin/inquiries/${id}/payment-sync`,{method:'POST',headers:authHeaders(),body:JSON.stringify(payload)}); const result=await res.json(); if(!res.ok)return alert(result.error||'Payment sync failed'); alert(sendEmail?(result.emailSent?'Payment saved and email sent':'Payment saved, but email was not sent'):'Payment status saved'); await loadInquiries(); await loadBookings(); const refreshed=allInquiries.find(x=>String(x.id)===String(id)); if(refreshed){currentInquiry=refreshed; openInquiryModal(id);}}
function v9InjectPaymentButtons(){const panel=document.querySelector('.v65-quote-panel, .booking-confirm-panel'); if(!panel||document.getElementById('v9SavePaymentBtn'))return; const row=panel.querySelector('.v65-action-row')||panel; const save=document.createElement('button'); save.id='v9SavePaymentBtn'; save.type='button'; save.textContent='Save Payment Status'; save.onclick=()=>savePaymentStatus(false); const mail=document.createElement('button'); mail.id='v9SendPaymentBtn'; mail.type='button'; mail.textContent='Send Payment / Invoice Email'; mail.onclick=()=>savePaymentStatus(true); row.appendChild(save); row.appendChild(mail);}
const v9OldOpenInquiryModal=typeof openInquiryModal==='function'?openInquiryModal:null; if(v9OldOpenInquiryModal){openInquiryModal=function(id){v9OldOpenInquiryModal(id); setTimeout(v9InjectPaymentButtons,150);};}
const v9OldShowTab=typeof showTab==='function'?showTab:null; if(v9OldShowTab){showTab=function(tab){v9OldShowTab(tab); setTimeout(v9InjectFilters,80);};}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(v9InjectFilters,600); setTimeout(v9RemoveDuplicateControls,1200);});


