(() => {
'use strict';
const $=id=>document.getElementById(id);
const frame=$('liveFrame'), pageSelect=$('pageSelect'), status=$('status');
const API_BASE='https://ceybreez-contact-api.ceybreez.workers.dev';
const PREFIX='CEYBREEZ_LIVE_BUILDER_V2:';
let selected=null, pageKey='home', history=[];
const pageConfig=v=>v==='welcome'?{file:'index.html',mode:'welcome',label:'Welcome Screen'}:v==='home'?{file:'index.html',mode:'home',label:'Home Page'}:{file:v,mode:'full',label:pageSelect.options[pageSelect.selectedIndex].text};
function setStatus(t,e=false){status.textContent=t;status.classList.toggle('error',e)}
function selectorFor(el){if(el.id)return '#'+CSS.escape(el.id);const parts=[];while(el&&el.nodeType===1&&el!==el.ownerDocument.body){let p=el.tagName.toLowerCase();if(el.classList.length)p+='.'+[...el.classList].slice(0,2).map(CSS.escape).join('.');const sib=[...el.parentElement.children].filter(x=>x.tagName===el.tagName);if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(el)+1})`;parts.unshift(p);el=el.parentElement}return parts.join(' > ')}
function loadPage(){selected=null;updateInspector();pageKey=pageSelect.value;const cfg=pageConfig(pageKey);setStatus(`Loading ${cfg.label}…`);frame.src=new URL(`../../${cfg.file}?cbuilder=${Date.now()}`,location.href).href}
frame.addEventListener('load',()=>{try{const d=frame.contentDocument,w=frame.contentWindow,cfg=pageConfig(pageKey);if(!d||!d.body)throw Error('Page is not accessible');if(cfg.mode==='home'){const welcome=d.getElementById('welcomeScreen');if(welcome)welcome.style.setProperty('display','none','important');const main=d.getElementById('mainSite');if(main){main.style.setProperty('display','block','important');main.style.setProperty('opacity','1','important');main.style.setProperty('visibility','visible','important')}d.body.classList.add('entered')}else if(cfg.mode==='welcome'){const main=d.getElementById('mainSite');if(main)main.style.setProperty('display','none','important');const welcome=d.getElementById('welcomeScreen');if(welcome){welcome.style.setProperty('display','flex','important');welcome.style.setProperty('opacity','1','important');welcome.style.setProperty('visibility','visible','important');welcome.classList.remove('hide')}d.body.classList.remove('entered')}
const st=d.createElement('style');st.id='cb-live-editor-style';st.textContent='[data-cb-selected="1"]{outline:3px solid #08a88a!important;outline-offset:2px!important;cursor:pointer!important}[data-cb-hover="1"]{outline:2px dashed #08a88a!important;outline-offset:2px!important}';d.head.appendChild(st);
d.addEventListener('click',onFrameClick,true);d.addEventListener('dblclick',onFrameDblClick,true);d.addEventListener('mouseover',e=>{if(e.target!==d.body&&e.target!==d.documentElement)e.target.dataset.cbHover='1'},true);d.addEventListener('mouseout',e=>delete e.target.dataset.cbHover,true);applyDraft();buildSections();setStatus(`${cfg.label} loaded. Dynamic sections are running from the actual page.`)}catch(err){setStatus('Could not open page: '+err.message,true)}});
function onFrameClick(e){const a=e.target.closest('a');if(a)e.preventDefault();e.stopPropagation();selectElement(e.target)}
function onFrameDblClick(e){e.preventDefault();e.stopPropagation();const el=e.target;if(['IMG','VIDEO','INPUT','SELECT','TEXTAREA'].includes(el.tagName))return;selectElement(el);el.contentEditable='true';el.focus();setStatus('Direct text editing enabled. Click outside when finished.');el.addEventListener('blur',()=>{el.contentEditable='false';recordChange(el)}, {once:true})}
function selectElement(el){if(selected)delete selected.dataset.cbSelected;selected=el;selected.dataset.cbSelected='1';$('selectedLabel').textContent=selectorFor(el);updateInspector()}
function buildSections(){const d=frame.contentDocument,list=$('sectionList');list.innerHTML='';const nodes=[...d.querySelectorAll('[data-section],main > section,body > section,header,footer')];const seen=new Set();nodes.forEach((el,i)=>{if(seen.has(el))return;seen.add(el);const b=document.createElement('button');b.textContent=el.dataset.section||el.id||el.className?.toString().split(' ')[0]||`${el.tagName} ${i+1}`;b.onclick=()=>{el.scrollIntoView({behavior:'smooth',block:'center'});selectElement(el)};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="empty">No sections found.</div>'}
function updateInspector(){const empty=$('emptyState'),ins=$('inspector');if(!selected){empty.hidden=false;ins.hidden=true;return}empty.hidden=true;ins.hidden=false;$('elementName').value=selectorFor(selected);$('textValue').value=['IMG','VIDEO'].includes(selected.tagName)?'':selected.innerText||'';$('linkRow').hidden=selected.tagName!=='A';$('linkValue').value=selected.getAttribute('href')||'';$('imageRow').hidden=selected.tagName!=='IMG';$('imageValue').value=selected.getAttribute('src')||'';const cs=frame.contentWindow.getComputedStyle(selected);$('colorValue').value=rgbHex(cs.color)||'#000000';$('bgValue').value=rgbHex(cs.backgroundColor)||'#ffffff';$('fontSize').value=parseInt(cs.fontSize)||16;$('radius').value=parseInt(cs.borderRadius)||0;$('padding').value=parseInt(cs.paddingTop)||0;$('margin').value=parseInt(cs.marginTop)||0;$('textAlign').value=['left','center','right'].includes(cs.textAlign)?cs.textAlign:''}
function rgbHex(v){const m=v&&v.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?'#'+[m[1],m[2],m[3]].map(x=>(+x).toString(16).padStart(2,'0')).join(''):null}
function recordChange(el){const s=selectorFor(el),patch={selector:s,html:el.innerHTML,attrs:{},style:el.getAttribute('style')||''};['href','src','class'].forEach(a=>{if(el.hasAttribute(a))patch.attrs[a]=el.getAttribute(a)});history.push(JSON.stringify(getDraft()));const draft=getDraft();draft[s]=patch;localStorage.setItem(PREFIX+pageKey,JSON.stringify(draft));updateInspector()}
function getDraft(){try{return JSON.parse(localStorage.getItem(PREFIX+pageKey)||'{}')}catch{return {}}}
function applyDraft(){const d=frame.contentDocument,draft=getDraft();Object.values(draft).forEach(p=>{try{const el=d.querySelector(p.selector);if(!el)return;if(p.html!==undefined)el.innerHTML=p.html;Object.entries(p.attrs||{}).forEach(([k,v])=>el.setAttribute(k,v));if(p.style!==undefined)el.setAttribute('style',p.style)}catch{}})}
function mutate(fn){if(!selected)return;history.push(JSON.stringify(getDraft()));fn(selected);recordChange(selected)}
$('textValue').addEventListener('change',e=>mutate(el=>el.innerText=e.target.value));$('linkValue').addEventListener('change',e=>mutate(el=>el.setAttribute('href',e.target.value)));$('imageValue').addEventListener('change',e=>mutate(el=>el.setAttribute('src',e.target.value)));
$('colorValue').addEventListener('input',e=>mutate(el=>el.style.color=e.target.value));$('bgValue').addEventListener('input',e=>mutate(el=>el.style.backgroundColor=e.target.value));$('fontSize').addEventListener('change',e=>mutate(el=>el.style.fontSize=e.target.value+'px'));$('radius').addEventListener('change',e=>mutate(el=>el.style.borderRadius=e.target.value+'px'));$('padding').addEventListener('change',e=>mutate(el=>el.style.padding=e.target.value+'px'));$('margin').addEventListener('change',e=>mutate(el=>el.style.margin=e.target.value+'px'));$('textAlign').addEventListener('change',e=>mutate(el=>el.style.textAlign=e.target.value));
$('hideBtn').onclick=()=>mutate(el=>el.style.display=el.style.display==='none'?'':'none');$('resetElementBtn').onclick=()=>{if(!selected)return;const draft=getDraft();delete draft[selectorFor(selected)];localStorage.setItem(PREFIX+pageKey,JSON.stringify(draft));loadPage()};
$('saveBtn').onclick=()=>{if(selected)recordChange(selected);setStatus(`Draft saved for ${pageConfig(pageKey).label} in this browser.`)};$('clearBtn').onclick=()=>{if(confirm('Clear all saved edits for this page?')){localStorage.removeItem(PREFIX+pageKey);loadPage()}};$('reloadBtn').onclick=loadPage;$('undoBtn').onclick=()=>{const prev=history.pop();if(prev!==undefined){localStorage.setItem(PREFIX+pageKey,prev);loadPage()}};pageSelect.onchange=loadPage;
document.querySelectorAll('.cb-devicebar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cb-devicebar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');frame.style.width=b.dataset.width});
$('uploadBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const file=e.target.files[0];if(!file||!selected)return;const token=localStorage.getItem('CEYBREEZ_ADMIN_TOKEN');if(!token){setStatus('Admin token not found. Log in to Admin first.',true);return}const fd=new FormData();fd.append('file',file);fd.append('folder','page-builder');setStatus('Uploading image…');try{const r=await fetch(API_BASE+'/api/admin/upload-image',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const data=await r.json();if(!r.ok||!data.url)throw Error(data.error||'Upload failed');mutate(el=>el.setAttribute('src',data.url));setStatus('Image uploaded and applied.')}catch(err){setStatus(err.message,true)}e.target.value=''};
loadPage();
})();
