(() => {
'use strict';
const $=id=>document.getElementById(id), frame=$('liveFrame'), pageSelect=$('pageSelect'), status=$('status');
const API_BASE='https://ceybreez-contact-api.ceybreez.workers.dev', PREFIX='CEYBREEZ_LIVE_BUILDER_V3:';
let selected=null,pageKey='home',history=[],redoStack=[],uploadTarget='image';
const pageConfig=v=>v==='welcome'?{file:'index.html',mode:'welcome',label:'Welcome Screen'}:v==='home'?{file:'index.html',mode:'home',label:'Home Page'}:{file:v,mode:'full',label:pageSelect.options[pageSelect.selectedIndex].text};
function setStatus(t,e=false){status.textContent=t;status.classList.toggle('error',e)}
function selectorFor(el){if(!el)return'';if(el.id)return '#'+CSS.escape(el.id);const parts=[];while(el&&el.nodeType===1&&el!==el.ownerDocument.body){let p=el.tagName.toLowerCase();if(el.classList.length)p+='.'+[...el.classList].filter(x=>!x.startsWith('cb-')).slice(0,2).map(CSS.escape).join('.');const sib=[...el.parentElement.children].filter(x=>x.tagName===el.tagName);if(sib.length>1)p+=`:nth-of-type(${sib.indexOf(el)+1})`;parts.unshift(p);el=el.parentElement}return parts.join(' > ')}
function loadPage(){selected=null;updateInspector();pageKey=pageSelect.value;const cfg=pageConfig(pageKey);setStatus(`Loading ${cfg.label}…`);frame.src=new URL(`../../${cfg.file}?cbuilder=${Date.now()}`,location.href).href}
frame.addEventListener('load',()=>{try{const d=frame.contentDocument,cfg=pageConfig(pageKey);if(!d||!d.body)throw Error('Page is not accessible');if(cfg.mode==='home'){const w=d.getElementById('welcomeScreen');if(w)w.style.setProperty('display','none','important');const m=d.getElementById('mainSite');if(m){m.style.setProperty('display','block','important');m.style.setProperty('opacity','1','important');m.style.setProperty('visibility','visible','important')}d.body.classList.add('entered')}else if(cfg.mode==='welcome'){const m=d.getElementById('mainSite');if(m)m.style.setProperty('display','none','important');const w=d.getElementById('welcomeScreen');if(w){w.style.setProperty('display','flex','important');w.style.setProperty('opacity','1','important');w.style.setProperty('visibility','visible','important');w.classList.remove('hide')}d.body.classList.remove('entered')}
let st=d.getElementById('cb-live-editor-style');if(!st){st=d.createElement('style');st.id='cb-live-editor-style';d.head.appendChild(st)}st.textContent='[data-cb-selected="1"]{outline:3px solid #08a88a!important;outline-offset:2px!important;cursor:pointer!important}[data-cb-hover="1"]{outline:2px dashed #08a88a!important;outline-offset:2px!important}';
d.addEventListener('click',onFrameClick,true);d.addEventListener('dblclick',onFrameDblClick,true);d.addEventListener('mouseover',e=>{if(e.target!==d.body&&e.target!==d.documentElement)e.target.dataset.cbHover='1'},true);d.addEventListener('mouseout',e=>delete e.target.dataset.cbHover,true);applyDraft();buildSections();buildLayers();setStatus(`${cfg.label} loaded. Live dynamic sections are included.`)}catch(err){setStatus('Could not open page: '+err.message,true)}});
function onFrameClick(e){const a=e.target.closest('a');if(a)e.preventDefault();e.stopPropagation();selectElement(e.target)}
function onFrameDblClick(e){e.preventDefault();e.stopPropagation();const el=e.target;if(['IMG','VIDEO','INPUT','SELECT','TEXTAREA'].includes(el.tagName))return;selectElement(el);el.contentEditable='true';el.focus();setStatus('Direct text editing enabled. Click outside when finished.');el.addEventListener('blur',()=>{el.contentEditable='false';recordChange(el)}, {once:true})}
function selectElement(el){if(selected)delete selected.dataset.cbSelected;selected=el;selected.dataset.cbSelected='1';$('selectedLabel').textContent=selectorFor(el);updateInspector()}
function buildSections(){const d=frame.contentDocument,list=$('sectionList');list.innerHTML='';const nodes=[...d.querySelectorAll('[data-section],main > section,body > section,header,footer')],seen=new Set();nodes.forEach((el,i)=>{if(seen.has(el))return;seen.add(el);const b=document.createElement('button');b.textContent=el.dataset.section||el.id||String(el.className||'').split(' ')[0]||`${el.tagName} ${i+1}`;b.onclick=()=>{el.scrollIntoView({behavior:'smooth',block:'center'});selectElement(el)};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="empty">No sections found.</div>'}
function buildLayers(){const d=frame.contentDocument,list=$('layerList');if(!d)return;list.innerHTML='';[...d.querySelectorAll('body > *, main > *, section > h1, section > h2, section > h3')].slice(0,120).forEach(el=>{const item=document.createElement('div');item.className='layer-item';item.innerHTML=`<b>${el.tagName.toLowerCase()}</b><span>${el.id?'#'+el.id:el.className?'.'+String(el.className).split(' ')[0]:el.textContent.trim().slice(0,28)}</span>`;item.onclick=()=>{el.scrollIntoView({behavior:'smooth',block:'center'});selectElement(el)};list.appendChild(item)})}
function rgbHex(v){const m=v&&v.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return m?'#'+[m[1],m[2],m[3]].map(x=>(+x).toString(16).padStart(2,'0')).join(''):null}
function num(v){const n=parseFloat(v);return Number.isFinite(n)?n:0}
function updateInspector(){const empty=$('emptyState'),ins=$('inspector'),se=$('settingsEmpty'),si=$('settingsInspector');if(!selected){empty.hidden=false;ins.hidden=true;se.hidden=false;si.hidden=true;return}empty.hidden=true;ins.hidden=false;se.hidden=true;si.hidden=false;$('elementName').textContent=selectorFor(selected);const cs=frame.contentWindow.getComputedStyle(selected);$('displayValue').value=['block','inline-block','flex','grid','none'].includes(cs.display)?cs.display:'';$('widthValue').value=selected.style.width||'';$('heightValue').value=selected.style.height||'';$('maxWidthValue').value=selected.style.maxWidth||'';$('minHeightValue').value=selected.style.minHeight||'';[['marginTop','marginTop'],['marginRight','marginRight'],['marginBottom','marginBottom'],['marginLeft','marginLeft'],['paddingTop','paddingTop'],['paddingRight','paddingRight'],['paddingBottom','paddingBottom'],['paddingLeft','paddingLeft']].forEach(([id,p])=>$(id).value=num(cs[p]));$('fontFamily').value=selected.style.fontFamily||cs.fontFamily||'';$('fontSize').value=num(cs.fontSize);$('fontWeight').value=['300','400','500','600','700','800'].includes(cs.fontWeight)?cs.fontWeight:'';$('lineHeight').value=selected.style.lineHeight||'';$('letterSpacing').value=selected.style.letterSpacing||'';$('textAlign').value=['left','center','right','justify'].includes(cs.textAlign)?cs.textAlign:'';$('colorValue').value=rgbHex(cs.color)||'#000000';$('bgValue').value=rgbHex(cs.backgroundColor)||'#ffffff';$('backgroundImage').value=selected.style.backgroundImage.replace(/^url\(["']?|["']?\)$/g,'')||'';$('backgroundSize').value=selected.style.backgroundSize||'';$('backgroundPosition').value=selected.style.backgroundPosition||'';$('radius').value=num(cs.borderRadius);$('borderWidth').value=num(cs.borderWidth);$('borderColor').value=rgbHex(cs.borderColor)||'#000000';$('boxShadow').value=selected.style.boxShadow||'';$('opacity').value=cs.opacity||1;$('textValue').value=['IMG','VIDEO'].includes(selected.tagName)?'':selected.innerHTML||'';$('linkRow').hidden=selected.tagName!=='A';$('linkValue').value=selected.getAttribute('href')||'';$('imageRow').hidden=selected.tagName!=='IMG';$('imageValue').value=selected.getAttribute('src')||'';$('classValue').value=selected.className||'';$('idValue').value=selected.id||''}
function getDraft(){try{return JSON.parse(localStorage.getItem(PREFIX+pageKey)||'{}')}catch{return {}}}
function snapshot(){return JSON.stringify(getDraft())}
function recordChange(el){if(!el)return;const s=selectorFor(el),draft=getDraft();draft[s]={selector:s,html:el.innerHTML,attrs:{},style:el.getAttribute('style')||''};['href','src','class','id'].forEach(a=>{if(el.hasAttribute(a))draft[s].attrs[a]=el.getAttribute(a)});localStorage.setItem(PREFIX+pageKey,JSON.stringify(draft));updateInspector();buildLayers()}
function applyDraft(){const d=frame.contentDocument,draft=getDraft();Object.values(draft).forEach(p=>{try{const el=d.querySelector(p.selector);if(!el)return;if(p.html!==undefined)el.innerHTML=p.html;Object.entries(p.attrs||{}).forEach(([k,v])=>el.setAttribute(k,v));if(p.style!==undefined)el.setAttribute('style',p.style)}catch{}})}
function mutate(fn){if(!selected)return;history.push(snapshot());redoStack=[];fn(selected);recordChange(selected)}
function bind(id,event,fn){$(id).addEventListener(event,e=>mutate(el=>fn(el,e.target.value)))}
bind('displayValue','change',(e,v)=>e.style.display=v);bind('widthValue','change',(e,v)=>e.style.width=v);bind('heightValue','change',(e,v)=>e.style.height=v);bind('maxWidthValue','change',(e,v)=>e.style.maxWidth=v);bind('minHeightValue','change',(e,v)=>e.style.minHeight=v);
['marginTop','marginRight','marginBottom','marginLeft','paddingTop','paddingRight','paddingBottom','paddingLeft'].forEach(id=>bind(id,'change',(e,v)=>e.style[id]=v+'px'));
bind('fontFamily','change',(e,v)=>e.style.fontFamily=v);bind('fontSize','change',(e,v)=>e.style.fontSize=v+'px');bind('fontWeight','change',(e,v)=>e.style.fontWeight=v);bind('lineHeight','change',(e,v)=>e.style.lineHeight=v);bind('letterSpacing','change',(e,v)=>e.style.letterSpacing=v);bind('textAlign','change',(e,v)=>e.style.textAlign=v);bind('colorValue','input',(e,v)=>e.style.color=v);bind('bgValue','input',(e,v)=>e.style.backgroundColor=v);bind('backgroundImage','change',(e,v)=>e.style.backgroundImage=v?`url("${v}")`:'' );bind('backgroundSize','change',(e,v)=>e.style.backgroundSize=v);bind('backgroundPosition','change',(e,v)=>e.style.backgroundPosition=v);bind('radius','change',(e,v)=>e.style.borderRadius=v+'px');bind('borderWidth','change',(e,v)=>{e.style.borderWidth=v+'px';e.style.borderStyle=v>0?'solid':''});bind('borderColor','input',(e,v)=>e.style.borderColor=v);bind('boxShadow','change',(e,v)=>e.style.boxShadow=v);bind('opacity','input',(e,v)=>e.style.opacity=v);
bind('textValue','change',(e,v)=>e.innerHTML=v);bind('linkValue','change',(e,v)=>e.setAttribute('href',v));bind('imageValue','change',(e,v)=>e.setAttribute('src',v));bind('classValue','change',(e,v)=>e.className=v);bind('idValue','change',(e,v)=>e.id=v);
$('hideBtn').onclick=()=>mutate(el=>el.style.display=el.style.display==='none'?'':'none');$('resetElementBtn').onclick=()=>{if(!selected)return;const draft=getDraft();delete draft[selectorFor(selected)];localStorage.setItem(PREFIX+pageKey,JSON.stringify(draft));loadPage()};
$('duplicateBtn').onclick=()=>{if(!selected)return;history.push(snapshot());const clone=selected.cloneNode(true);selected.after(clone);selectElement(clone);recordChange(clone)};$('deleteBtn').onclick=()=>{if(!selected||!confirm('Delete selected element from this draft?'))return;history.push(snapshot());const parent=selected.parentElement;selected.remove();selected=parent;recordChange(parent)};
function addBlock(type){const d=frame.contentDocument,parent=selected&&selected.tagName!=='IMG'&&selected.tagName!=='INPUT'?selected:d.querySelector('main')||d.body;let el;const make=h=>{const t=d.createElement('template');t.innerHTML=h.trim();return t.content.firstElementChild};const map={section:'<section style="padding:70px 20px"><h2>New Section</h2><p>Add your content here.</p></section>',container:'<div style="max-width:1200px;margin:auto;padding:20px">Container</div>',columns:'<div style="display:grid;grid-template-columns:1fr 1fr;gap:20px"><div>Column 1</div><div>Column 2</div></div>',heading:'<h2>New Heading</h2>',text:'<p>New text content</p>',button:'<a href="#" style="display:inline-block;padding:12px 22px;border-radius:6px;background:#087f75;color:#fff;text-decoration:none">Button</a>',image:'<img src="images/cover.jpg" alt="New image" style="max-width:100%;height:auto">',card:'<div style="padding:24px;border-radius:12px;background:#fff;box-shadow:0 10px 30px rgba(0,0,0,.12)"><h3>Card title</h3><p>Card content</p></div>',spacer:'<div style="height:60px"></div>',divider:'<hr style="border:0;border-top:1px solid #d8e2e8">'};el=make(map[type]);parent.appendChild(el);selectElement(el);recordChange(parent);el.scrollIntoView({behavior:'smooth',block:'center'})}
document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addBlock(b.dataset.add));
$('saveBtn').onclick=()=>{if(selected)recordChange(selected);setStatus(`Draft saved for ${pageConfig(pageKey).label}.`)};$('clearBtn').onclick=()=>{if(confirm('Clear all saved edits for this page?')){localStorage.removeItem(PREFIX+pageKey);history=[];redoStack=[];loadPage()}};$('reloadBtn').onclick=loadPage;$('undoBtn').onclick=()=>{const prev=history.pop();if(prev!==undefined){redoStack.push(snapshot());localStorage.setItem(PREFIX+pageKey,prev);loadPage()}};$('redoBtn').onclick=()=>{const next=redoStack.pop();if(next!==undefined){history.push(snapshot());localStorage.setItem(PREFIX+pageKey,next);loadPage()}};$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({page:pageKey,edits:getDraft()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ceybreez-${pageKey}-draft.json`;a.click();URL.revokeObjectURL(a.href)};pageSelect.onchange=loadPage;
document.querySelectorAll('.cb-devicebar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.cb-devicebar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');frame.style.width=b.dataset.width});
document.querySelectorAll('[data-left-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-left-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.left-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.leftTab+'Tab').classList.add('active')});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.right-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab+'Tab').classList.add('active')});
function startUpload(target){uploadTarget=target;$('fileInput').click()}$('uploadBtn').onclick=()=>startUpload('image');$('mediaUploadBtn').onclick=()=>startUpload('image');$('bgUploadBtn').onclick=()=>startUpload('background');$('fileInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const token=localStorage.getItem('CEYBREEZ_ADMIN_TOKEN');if(!token){setStatus('Admin token not found. Log in to Admin first.',true);return}const fd=new FormData();fd.append('file',file);fd.append('folder','page-builder');setStatus('Uploading image…');try{const r=await fetch(API_BASE+'/api/admin/upload-image',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});const data=await r.json();if(!r.ok||!data.url)throw Error(data.error||'Upload failed');if(selected){if(uploadTarget==='background')mutate(el=>el.style.backgroundImage=`url("${data.url}")`);else if(selected.tagName==='IMG')mutate(el=>el.setAttribute('src',data.url));else{const img=frame.contentDocument.createElement('img');img.src=data.url;img.style.maxWidth='100%';selected.appendChild(img);recordChange(selected)}}setStatus('Image uploaded and applied.')}catch(err){setStatus(err.message,true)}e.target.value=''};
loadPage();
})();
